package com.kingbase.db.replication.bundle.i18n.messages;

import org.eclipse.osgi.util.NLS;

public class Messages extends NLS {
	private static final String BUNDLE_NAME = "com.kingbase.db.replication.bundle.i18n.messages.messages"; 
	public static String ConnectionPasswordDialog_Authentication;
	public static String ConnectionPasswordDialog_btnCanel;
	public static String ConnectionPasswordDialog_btnConfirm;
	public static String ConnectionPasswordDialog_Password;
	public static String ConnectionPasswordDialog_Save_password;
	public static String ConnectionPasswordDialog_user_and_password_is_not_match;
	public static String ConnectionPasswordDialog_User_Credentials;
	public static String ConnectionPasswordDialog_Username;
	public static String CreateReleaseDialog_btnCancel;
	public static String CreateReleaseDialog_btnCheck;
	public static String CreateReleaseDialog_btnConfirm;
	public static String CreateReleaseDialog_create_release;
	public static String CreateReleaseDialog_Filter_conditions;
	public static String CreateReleaseDialog_please_check;
	public static String CreateReleaseDialog_Prompt;
	public static String CreateReleaseDialog_release_Already_exist;
	public static String CreateReleaseDialog_release_create_success;
	public static String CreateReleaseDialog_release_name;
	public static String CreateReleaseDialog_release_name_is_null;
	public static String CreateReleaseDialog_release_options;
	public static String CreateReleaseDialog_release_table_selection;
	public static String CreateReleaseDialog_release_update_success;
	public static String CreateReleaseDialog_select_tables;
	public static String CreateReleaseDialog_Test_success;
	public static String CreateSourceConnectionDialog_Drive_name;
	public static String CreateSourceConnectionDialog_Drive_path;
	public static String CreateSourceConnectionDialog_browse;
	public static String CreateSourceConnectionDialog_Register_release;
	public static String CreateSourceConnectionDialog_Registered_subscription;
	public static String CreateSourceConnectionDialog_address;
	public static String CreateSourceConnectionDialog_address_is_null;
	public static String CreateSourceConnectionDialog_cancel;
	public static String CreateSourceConnectionDialog_check;
	public static String CreateSourceConnectionDialog_confirm;
	public static String CreateSourceConnectionDialog_name;
	public static String CreateSourceConnectionDialog_name_is_null;
	public static String CreateSourceConnectionDialog_password;
	public static String CreateSourceConnectionDialog_password_is_null;
	public static String CreateSourceConnectionDialog_port;
	public static String CreateSourceConnectionDialog_port_is_null;
	public static String CreateSourceConnectionDialog_Please_Rename;
	public static String CreateSourceConnectionDialog_Prompt;
	public static String CreateSourceConnectionDialog_save_password;
	public static String CreateSourceConnectionDialog_Server_is_not_connected;
	public static String CreateSourceConnectionDialog_Server_test_connection_fail;
	public static String CreateSourceConnectionDialog_Server_test_connection_successful;
	public static String CreateSourceConnectionDialog_user;
	public static String CreateSourceConnectionDialog_user_is_null;
	public static String CreateSubscribeDialog_cancel;
	public static String CreateSubscribeDialog_confirm;
	public static String CreateSubscribeDialog_create_subscription;
	public static String CreateSubscribeDialog_create_subscription_success;
	public static String CreateSubscribeDialog_database;
	public static String CreateSubscribeDialog_name;
	public static String CreateSubscribeDialog_please_change_release;
	public static String CreateSubscribeDialog_please_rename;
	public static String CreateSubscribeDialog_Prompt;
	public static String CreateSubscribeDialog_release_selection;
	public static String CreateSubscribeDialog_release_server_name;
	public static String CreateSubscribeDialog_Sub_Option;
	public static String CreateSubscribeDialog_Subscription_name_cannot_be_empty;
	public static String CreateSubscribeDialog_table_is_not_exist;
	public static String CreateSubscribeDialog_update_subscription_success;
	public static String DDLdialog_Please_select_the_required_publication;
	public static String DDLdialog_release_change;
	public static String ReplicationView_refresh;
	public static String DDLdialog_sysc_ddl;
	public static String DDLdialog_sysc_success;
	public static String DeleteReleaseDialog_cancel;
	public static String DeleteReleaseDialog_confirm;
	public static String DeleteReleaseDialog_confirm_deletion;
	public static String DeleteReleaseDialog_if_delete_current_release;
	public static String NavigaterActionGroup_Collapse_All;
	public static String ReplicationFolder_release;
	public static String ReplicationFolder_subscribe;
	public static String ReplicationRoot_Data_sysc;
	public static String ReplicationView_close_subscribe;
	public static String ReplicationView_create_release;
	public static String ReplicationView_create_subscriber;
	public static String ReplicationView_delete_release;
	public static String ReplicationView_delete_server;
	public static String ReplicationView_delete_subsciber;
	public static String ReplicationView_if_delete_this_server;
	public static String ReplicationView_open_subscriber;
	public static String ReplicationView_Prompt;
	public static String ReplicationView_Registered_release_server;
	public static String ReplicationView_Registered_subscriber_server;
	public static String ReplicationView_sync_subscriber;
	public static String ReplicationView_sync_table;
	public static String ReplicationView_syncEnable;
	public static String ReplicationView_syncEnable_success;
	public static String ReplicationView_update_release;
	public static String ReplicationView_update_release_server;
	public static String ReplicationView_update_subscriber;
	public static String ReplicationView_Update_subscriber_server;
	public static String ReplicationView_Subscription_status_diagram;
	public static String ReplicationView_Sync_table_success;
	public static String ReplicationView_Sync_subscription_success;
	public static String ReplicationView_Synchronous_DDL;
	public static String ReplicationView_Disable_subscription_success;
	public static String ReplicationView_Enable_subscription_success;
	
	public static String SubscribeDataInfo_could_not_find_server;
	public static String ThisSubscribeDialog_Clear_existing_data;
	public static String ThisSubscribeDialog_cancel;
	public static String ThisSubscribeDialog_close;
	public static String ThisSubscribeDialog_close_current_subscription;
	public static String ThisSubscribeDialog_confirm;
	public static String ThisSubscribeDialog_delete_current_subscription;
	public static String ThisSubscribeDialog_delete_subscription;
	public static String ThisSubscribeDialog_if_syncTable;
	public static String ThisSubscribeDialog_open_current_subscription;
	public static String ThisSubscribeDialog_open_subscription;
	public static String ThisSubscribeDialog_sync;
	public static String ThisSubscribeDialog_syncTable;
	public static String ThisSubscribeDialog_sysc_other;
	static {
		// initialize resource bundle
		NLS.initializeMessages(BUNDLE_NAME, Messages.class);
	}

	private Messages() {
	}
}
